import type { Language } from "@/lib/i18n"

// ============================================================
// Game i18n
// ============================================================
//
// This file contains translations for the text generated by
// lib/game.ts. It deliberately does NOT contain game logic.
//
// English is the source language used by game.ts.
// Spanish is the additional UI/game language.
//
// ============================================================

export type GameLanguage = Language

// ============================================================
// Stats
// ============================================================

export const STAT_META_I18N = {
  en: {
    song: {
      label: "Song",
      short: "SONG",
    },
    staging: {
      label: "Staging",
      short: "STAGE",
    },
  },

  es: {
    song: {
      label: "Canción",
      short: "CANCIÓN",
    },
    staging: {
      label: "Puesta en escena",
      short: "ESCENA",
    },
  },
} as const

export function getStatLabel(
  stat: "song" | "staging",
  language: GameLanguage,
): string {
  return STAT_META_I18N[language][stat].label
}

export function getStatShort(
  stat: "song" | "staging",
  language: GameLanguage,
): string {
  return STAT_META_I18N[language][stat].short
}

// ============================================================
// Countries
// ============================================================

const COUNTRY_NAMES_ES: Record<string, string> = {
  se: "Suecia",
  it: "Italia",
  ua: "Ucrania",
  fi: "Finlandia",
  ch: "Suiza",
  fr: "Francia",
  nl: "Países Bajos",
  hr: "Croacia",
  no: "Noruega",
  au: "Australia",
  at: "Austria",
  gr: "Grecia",
  ee: "Estonia",
  es: "España",
  pt: "Portugal",
  be: "Bélgica",
  cy: "Chipre",
  az: "Azerbaiyán",
  am: "Armenia",
  lt: "Lituania",
  rs: "Serbia",
  is: "Islandia",
  md: "Moldavia",
  gb: "Reino Unido",
  ie: "Irlanda",
  si: "Eslovenia",
  de: "Alemania",
  pl: "Polonia",
  cz: "Chequia",
  lv: "Letonia",
  ge: "Georgia",
  mt: "Malta",
  al: "Albania",
  sm: "San Marino",
  bg: "Bulgaria",
  dk: "Dinamarca",
  lu: "Luxemburgo",
  me: "Montenegro",
  ro: "Rumanía",
  mk: "Macedonia del Norte",
  sk: "Eslovaquia",
  hu: "Hungría",
  ba: "Bosnia y Herzegovina",
}

export function getCountryName(
  countryId: string,
  originalName: string,
  language: GameLanguage,
): string {
  if (language === "en") return originalName
  return COUNTRY_NAMES_ES[countryId] ?? originalName
}

// ============================================================
// Cities
// ============================================================

const CITY_NAMES_ES: Record<string, string> = {
  Kyiv: "Kiev",
  Chisinau: "Chisináu",
  Bucharest: "Bucarest",
  Prague: "Praga",
  Warsaw: "Varsovia",
  Brussels: "Bruselas",
  Copenhagen: "Copenhague",
  Luxembourg: "Luxemburgo",
  Lisbon: "Lisboa",
  Athens: "Atenas",
  Vienna: "Viena",
  Rome: "Roma",
  Stockholm: "Estocolmo",
  Helsinki: "Helsinki",
  Oslo: "Oslo",
  Reykjavik: "Reikiavik",
  Madrid: "Madrid",
  London: "Londres",
  Dublin: "Dublín",
  Berlin: "Berlín",
  Amsterdam: "Ámsterdam",
  Belgrade: "Belgrado",
  Sofia: "Sofía",
  Skopje: "Skopie",
  Bratislava: "Bratislava",
  Budapest: "Budapest",
  Sarajevo: "Sarajevo",
  Tirana: "Tirana",
  Podgorica: "Podgorica",
  Valletta: "La Valeta",
  Vilnius: "Vilna",
  Riga: "Riga",
  Tbilisi: "Tiflis",
  Yerevan: "Ereván",
  Baku: "Bakú",
  Milan: "Milán",
  Naples: "Nápoles",
  Turin: "Turín",
  Munich: "Múnich",
  Cologne: "Colonia",
  Marseille: "Marsella",
  Geneva: "Ginebra",
  Zurich: "Zúrich",
  "The Hague": "La Haya",
  Seville: "Sevilla",
  Porto: "Oporto",
  Krakow: "Cracovia",
  Wrocław: "Breslavia",
  Burgas: "Burgas",
}

export function getCityName(
  city: string,
  language: GameLanguage,
): string {
  if (language === "en") return city
  return CITY_NAMES_ES[city] ?? city
}

// ============================================================
// Genres
// ============================================================

const GENRE_NAMES_ES: Record<string, string> = {
  "Power Ballad": "Balada épica",
  "Europop Banger": "Europop explosivo",
  "Ethno-Pop": "Etno-pop",
  "Dark Pop": "Pop oscuro",
  "Techno Rave": "Techno rave",
  "Folk Anthem": "Himno folk",
  "Operatic Pop": "Pop operístico",
  "Rock Anthem": "Himno rock",
  "Disco Revival": "Revival disco",
  "Synth Ballad": "Balada synth",
  "Hip-Hop": "Hip-hop",
  Chanson: "Chanson",
}

export function getGenreName(
  genreName: string,
  language: GameLanguage,
): string {
  if (language === "en") return genreName
  return GENRE_NAMES_ES[genreName] ?? genreName
}

// ============================================================
// Decision roles
// ============================================================

const DECISION_ROLES_ES: Record<string, string> = {
  Songwriter: "Compositor",
  "Stage Director": "Director escénico",
  Producer: "Productor",
  Choreographer: "Coreógrafo",
  "Head of Delegation": "Jefe de delegación",
  "Set Designer": "Diseñador de escenografía",
}

export function getDecisionRole(
  role: string,
  language: GameLanguage,
): string {
  if (language === "en") return role
  return DECISION_ROLES_ES[role] ?? role
}

// ============================================================
// Decisions
// ============================================================

type DecisionTranslation = {
  role: string
  prompt: string
  left: string
  right: string
}

const DECISIONS_ES: Record<string, DecisionTranslation> = {
  bridge: {
    role: "Compositor",
    prompt:
      "El presupuesto es ajustado. ¿Lo gastas reescribiendo el puente o en una espectacular acrobacia aérea?",
    left: "Reescribir el puente",
    right: "Acrobacia aérea",
  },

  raw: {
    role: "Director escénico",
    prompt:
      "¿Reduces el arreglo para crear un momento vocal más puro o gastas el presupuesto en pirotecnia?",
    left: "Momento vocal puro",
    right: "Pirotecnia",
  },

  keychange: {
    role: "Compositor",
    prompt:
      "¿Añades el clásico cambio de tono de Eurovisión para darle dramatismo o preparas una espectacular transformación de vestuario?",
    left: "Gran cambio de tono",
    right: "Transformación de vestuario",
  },

  orchestra: {
    role: "Productor",
    prompt:
      "¿Grabamos una elaborada sección orquestal para la canción o construimos un enorme fondo LED para el escenario?",
    left: "Sección orquestal",
    right: "Gran escenario LED",
  },

  dance: {
    role: "Coreógrafo",
    prompt:
      "¿Ajustas el tempo para crear una versión más radiofónica o preparas un baile viral y listo para convertirse en meme?",
    left: "Ajustar el tempo",
    right: "Baile viral",
  },

  guest: {
    role: "Jefe de delegación",
    prompt:
      "¿Traes a un compositor estrella como invitado o a un coreógrafo famoso? Solo puedes permitirte uno.",
    left: "Compositor invitado",
    right: "Coreógrafo famoso",
  },

  rehearsal: {
    role: "Director escénico",
    prompt:
      "¿Dedicas los últimos ensayos a perfeccionar la voz o a pulir la puesta en escena?",
    left: "Perfeccionar la voz",
    right: "Perfeccionar la puesta en escena",
  },

  silence: {
    role: "Compositor",
    prompt:
      "¿Eliminas la segunda estrofa para crear un silencio dramático o llenas el escenario con un espectáculo de máquinas de viento?",
    left: "Silencio dramático",
    right: "Espectáculo de viento",
  },

  language: {
    role: "Compositor",
    prompt:
      "¿Traducimos la letra al inglés para llegar a un público más amplio o la mantenemos en el idioma nativo y apostamos por una puesta en escena impactante?",
    left: "Cantar en inglés",
    right: "Idioma nativo + visuales",
  },

  melody: {
    role: "Productor",
    prompt:
      "¿Inviertes en una melodía inolvidable o en proyecciones cinematográficas para el fondo del escenario?",
    left: "La melodía",
    right: "Proyecciones",
  },

  band: {
    role: "Diseñador de escenografía",
    prompt:
      "¿Pones una banda en directo sobre el escenario para darle autenticidad o mantienes una escenografía limpia y minimalista que deje respirar a la canción?",
    left: "Banda en directo",
    right: "Escenografía minimalista",
  },

  finale: {
    role: "Director escénico",
    prompt:
      "¿Rehaces el último estribillo para crear un clímax mayor o activas chorros de fuego en la última nota?",
    left: "Rehacer el estribillo",
    right: "Chorros de fuego",
  },
}

export function getDecisionTranslation(
  id: string,
  language: GameLanguage,
): DecisionTranslation | null {
  if (language === "en") return null
  return DECISIONS_ES[id] ?? null
}

export function translateDecisionRole(
  id: string,
  originalRole: string,
  language: GameLanguage,
): string {
  if (language === "en") return originalRole

  return DECISIONS_ES[id]?.role ?? getDecisionRole(originalRole, language)
}

export function translateDecisionPrompt(
  id: string,
  originalPrompt: string,
  language: GameLanguage,
): string {
  if (language === "en") return originalPrompt

  return DECISIONS_ES[id]?.prompt ?? originalPrompt
}

export function translateDecisionChoice(
  id: string,
  side: "left" | "right",
  originalLabel: string,
  language: GameLanguage,
): string {
  if (language === "en") return originalLabel

  return DECISIONS_ES[id]?.[side] ?? originalLabel
}

// ============================================================
// Contest events
// ============================================================

const EVENTS_ES: Record<string, string> = {
  viral:
    "Un clip de los ensayos se hace viral en TikTok durante la noche.",

  cold:
    "El cantante principal se resfría pocos días antes de la final.",

  malfunction:
    "Un problema con el vestuario ocurre durante el ensayo general.",

  standing:
    "El pabellón entero se pone en pie y ovaciona durante la canción.",

  pyro_fail:
    "La pirotecnia falla durante la retransmisión en directo.",

  critics:
    "Los críticos consideran que la composición es la mejor del año.",

  draw:
    "Te toca una de las temidas primeras posiciones del orden de actuación.",

  primetime:
    "Consigues la codiciada última posición del orden de actuación.",

  nerves:
    "Los nervios hacen que la voz en directo tiemble durante la actuación.",

  perfect:
    "Una actuación en directo impecable y perfectamente afinada.",

  meme:
    "La puesta en escena se convierte inmediatamente en un meme de internet.",

  backing:
    "Un corte de corriente interrumpe la pista de acompañamiento durante un instante.",
}

export function translateContestEvent(
  id: string,
  originalText: string,
  language: GameLanguage,
): string {
  if (language === "en") return originalText
  return EVENTS_ES[id] ?? originalText
}

// ============================================================
// Withdrawal reasons
// ============================================================

const WITHDRAWAL_REASONS_ES: Record<string, string> = {
  "withdrew citing the rising cost of participation.":
    "se retiró alegando el aumento del coste de participación.",

  "pulled out after national broadcaster budget cuts.":
    "se retiró tras los recortes presupuestarios de su televisión pública.",

  "sat out this year over an EBU membership dispute.":
    "no participará este año debido a una disputa relacionada con su pertenencia a la UER.",

  "withdrew following a broadcasting-rights disagreement.":
    "se retiró tras un desacuerdo sobre los derechos de retransmisión.",

  "skipped this edition amid internal broadcaster restructuring.":
    "no participará en esta edición debido a una reestructuración interna de su televisión pública.",

  "pulled out over a political controversy surrounding the host.":
    "se retiró debido a una controversia política relacionada con el país anfitrión.",

  "failed to secure government funding before the deadline.":
    "no consiguió financiación gubernamental antes de la fecha límite.",

  "opted out after a run of poor results and low viewership.":
    "decidió no participar tras una serie de malos resultados y una baja audiencia.",

  "withdrew due to a scheduling clash with a national election.":
    "se retiró debido a un conflicto de fechas con unas elecciones nacionales.",

  "suspended its entry over a sponsorship funding shortfall.":
    "suspendió su participación debido a la falta de financiación de patrocinadores.",

  "withdrew after failing to reach an agreement with the national broadcaster.":
    "se retiró tras no alcanzar un acuerdo con la televisión pública nacional.",

  "pulled out following a change in the broadcaster's leadership.":
    "se retiró tras un cambio en la dirección de la televisión pública.",

  "withdrew after the broadcaster redirected its budget to domestic programming.":
    "se retiró después de que la televisión pública destinara su presupuesto a programación nacional.",

  "decided to skip this edition due to rising production costs.":
    "decidió no participar en esta edición debido al aumento de los costes de producción.",

  "withdrew after failing to secure a suitable Eurovision venue.":
    "se retiró tras no conseguir un recinto adecuado para Eurovisión.",

  "pulled out following disagreements over the selection process.":
    "se retiró tras desacuerdos sobre el proceso de selección.",

  "withdrew after its planned national selection was cancelled.":
    "se retiró después de que se cancelara su proceso de selección nacional.",

  "skipped this year's contest due to concerns over audience interest.":
    "no participará este año debido a dudas sobre el interés de la audiencia.",

  "withdrew after the broadcaster failed to meet the participation deadline.":
    "se retiró después de que la televisión pública no cumpliera el plazo de participación.",

  "pulled out following a dispute over broadcasting obligations.":
    "se retiró tras una disputa sobre sus obligaciones de retransmisión.",

  "withdrew after its Eurovision budget was frozen pending a financial review.":
    "se retiró después de que su presupuesto para Eurovisión quedara congelado a la espera de una revisión financiera.",

  "decided not to participate while the broadcaster reviews its international strategy.":
    "decidió no participar mientras la televisión pública revisa su estrategia internacional.",

  "withdrew after failing to secure a confirmed artist for the contest.":
    "se retiró tras no conseguir un artista confirmado para el concurso.",

  "pulled out after its selected artist became unavailable.":
    "se retiró después de que el artista seleccionado dejara de estar disponible.",

  "withdrew following concerns over the cost of staging and promotion.":
    "se retiró debido a las preocupaciones por el coste de la puesta en escena y la promoción.",

  "skipped the contest while undergoing a major restructuring of its public broadcaster.":
    "no participará mientras su televisión pública atraviesa una importante reestructuración.",

  "withdrew after negotiations with the EBU failed to resolve participation terms.":
    "se retiró después de que las negociaciones con la UER no resolvieran las condiciones de participación.",

  "pulled out following a dispute over the allocation of broadcasting fees.":
    "se retiró tras una disputa sobre el reparto de las tasas de retransmisión.",

  "withdrew after the national broadcaster announced a temporary spending freeze.":
    "se retiró después de que la televisión pública anunciara una congelación temporal del gasto.",

  "decided to take a one-year break from the contest due to financial pressures.":
    "decidió tomarse un año de descanso del concurso debido a las presiones económicas.",

  "withdrew following uncertainty over the broadcaster's future funding.":
    "se retiró debido a la incertidumbre sobre la futura financiación de la televisión pública.",

  "pulled out after failing to secure sufficient commercial sponsorship.":
    "se retiró tras no conseguir suficiente patrocinio comercial.",

  "withdrew amid uncertainty surrounding the country's broadcasting licence.":
    "se retiró en medio de la incertidumbre sobre la licencia de retransmisión del país.",

  "skipped this edition while reviewing its long-term participation strategy.":
    "no participará en esta edición mientras revisa su estrategia de participación a largo plazo.",

  "withdrew after the broadcaster faced unexpected technical and production costs.":
    "se retiró después de que la televisión pública afrontara costes técnicos y de producción inesperados.",

  "pulled out following a change in national broadcasting policy.":
    "se retiró tras un cambio en la política nacional de retransmisión.",

  "withdrew after its planned entry was deemed financially unviable.":
    "se retiró después de que su propuesta fuera considerada económicamente inviable.",

  "decided to skip the contest due to competing domestic broadcasting priorities.":
    "decidió no participar debido a otras prioridades de la televisión pública nacional.",

  "withdrew following an unresolved dispute with the national selection committee.":
    "se retiró tras una disputa sin resolver con el comité nacional de selección.",

  "pulled out after the broadcaster postponed its Eurovision preparations.":
    "se retiró después de que la televisión pública aplazara sus preparativos para Eurovisión.",
}

export function translateWithdrawalReason(
  reason: string,
  language: GameLanguage,
): string {
  if (language === "en") return reason
  return WITHDRAWAL_REASONS_ES[reason] ?? reason
}

// ============================================================
// Placement labels
// ============================================================

export const PLACEMENT_LABELS_ES = {
  didNotQualify: "No se ha clasificado",
  winner: "GANADOR",
  podium: "Podio",
  top5: "Top 5",
  leftSide: "Mitad alta de la clasificación",
  qualified: "Clasificado",
} as const

export function translatePlacementLabel(
  original: string,
  language: GameLanguage,
): string {
  if (language === "en") return original

  switch (original) {
    case "Did not qualify":
      return PLACEMENT_LABELS_ES.didNotQualify

    case "WINNER":
      return PLACEMENT_LABELS_ES.winner

    case "Podium":
      return PLACEMENT_LABELS_ES.podium

    case "Top 5":
      return PLACEMENT_LABELS_ES.top5

    case "Left side of the board":
      return PLACEMENT_LABELS_ES.leftSide

    case "Qualified":
      return PLACEMENT_LABELS_ES.qualified

    default:
      return original
  }
}

// ============================================================
// Placement flavour
// ============================================================

export function getPlacementFlavor(
  entry: {
    qualified: boolean
    position: number
    semiPosition: number
    semiPoints: number
  },
  finalists: number,
  language: GameLanguage,
): string {
  if (language === "en") {
    if (!entry.qualified) {
      return `Knocked out in the semi-final — ${entry.semiPosition}${getOrdinal(
        entry.semiPosition,
      )} with ${entry.semiPoints} pts, just short of the Grand Final.`
    }

    if (entry.position === 1) {
      return "Douze points! Your country wins the Grand Final and hosts next year."
    }

    if (entry.position <= 3) {
      return "A place on the podium — the fans are ecstatic."
    }

    if (entry.position <= 5) {
      return "A confident Top 5 finish. The delegation is thrilled."
    }

    if (entry.position <= 10) {
      return "A respectable finish on the left side of the scoreboard."
    }

    return `${entry.position}th of ${finalists} finalists. You made the final, but the points stayed shy.`
  }

  if (!entry.qualified) {
    return `Eliminado en la semifinal — ${entry.semiPosition}${getOrdinal(
      entry.semiPosition,
    )} con ${entry.semiPoints} puntos, quedándose a las puertas de la Gran Final.`
  }

  if (entry.position === 1) {
    return "¡Doce puntos! Tu país gana la Gran Final y organizará el concurso del próximo año."
  }

  if (entry.position <= 3) {
    return "Un puesto en el podio — los fans están eufóricos."
  }

  if (entry.position <= 5) {
    return "Un sólido Top 5. La delegación está encantada."
  }

  if (entry.position <= 10) {
    return "Un resultado respetable en la mitad alta de la clasificación."
  }

  return `${entry.position}.º de ${finalists} finalistas. Llegaste a la final, pero los puntos no fueron suficientes.`
}

// ============================================================
// Ordinals
// ============================================================

export function getOrdinal(
  n: number,
  language: GameLanguage = "en",
): string {
  if (language === "es") {
    return "º"
  }

  const s = ["th", "st", "nd", "rd"]
  const v = n % 100

  return s[(v - 20) % 10] ?? s[v] ?? s[0]
}

// ============================================================
// Season title
// ============================================================

export function getTranslatedSeasonTitle(
  year: number,
  hostName: string,
  city: string,
  language: GameLanguage,
): string {
  const translatedCity = getCityName(city, language)
  const translatedCountry = hostName

  if (language === "en") {
    return `${translatedCity} (${translatedCountry}) ${year}`
  }

  return `${translatedCity} (${translatedCountry}) ${year}`
}

// ============================================================
// Generic game text helper
// ============================================================

const GENERIC_ES: Record<string, string> = {
  Song: "Canción",
  SONG: "CANCIÓN",
  Staging: "Puesta en escena",
  STAGE: "ESCENA",

  "Did not qualify": "No se ha clasificado",
  WINNER: "GANADOR",
  Podium: "Podio",
  "Top 5": "Top 5",
  "Left side of the board": "Mitad alta de la clasificación",
  Qualified: "Clasificado",

  Songwriter: "Compositor",
  "Stage Director": "Director escénico",
  Producer: "Productor",
  Choreographer: "Coreógrafo",
  "Head of Delegation": "Jefe de delegación",
  "Set Designer": "Diseñador de escenografía",

  "Power Ballad": "Balada épica",
  "Europop Banger": "Europop explosivo",
  "Ethno-Pop": "Etno-pop",
  "Dark Pop": "Pop oscuro",
  "Techno Rave": "Techno rave",
  "Folk Anthem": "Himno folk",
  "Operatic Pop": "Pop operístico",
  "Rock Anthem": "Himno rock",
  "Disco Revival": "Revival disco",
  "Synth Ballad": "Balada synth",
  "Hip-Hop": "Hip-hop",
  Chanson: "Chanson",
}

export function translateGameText(
  text: string,
  language: GameLanguage,
): string {
  if (language === "en") return text
  return GENERIC_ES[text] ?? text
}

// ============================================================
// Complete decision object helper
// ============================================================

export function translateDecision(
  decision: {
    id: string
    role: string
    prompt: string
    left: { label: string }
    right: { label: string }
  },
  language: GameLanguage,
) {
  if (language === "en") {
    return {
      ...decision,
      role: decision.role,
      prompt: decision.prompt,
      left: decision.left.label,
      right: decision.right.label,
    }
  }

  return {
    ...decision,
    role: translateDecisionRole(
      decision.id,
      decision.role,
      language,
    ),
    prompt: translateDecisionPrompt(
      decision.id,
      decision.prompt,
      language,
    ),
    left: translateDecisionChoice(
      decision.id,
      "left",
      decision.left.label,
      language,
    ),
    right: translateDecisionChoice(
      decision.id,
      "right",
      decision.right.label,
      language,
    ),
  }
}

// ============================================================
// Complete contest event helper
// ============================================================

export function translateEvent(
  event: {
    id: string
    text: string
    effect: Record<string, number>
  },
  language: GameLanguage,
) {
  return {
    ...event,
    text: translateContestEvent(
      event.id,
      event.text,
      language,
    ),
  }
}

// ============================================================
// Complete withdrawal helper
// ============================================================

export function translateWithdrawal(
  withdrawal: {
    country: {
      id: string
      name: string
    }
    reason: string
  },
  language: GameLanguage,
) {
  return {
    ...withdrawal,
    country: {
      ...withdrawal.country,
      name: getCountryName(
        withdrawal.country.id,
        withdrawal.country.name,
        language,
      ),
    },
    reason: translateWithdrawalReason(
      withdrawal.reason,
      language,
    ),
  }
}

// ============================================================
// Complete song helper
// ============================================================
//
// Song titles and artist names are intentionally NOT translated.
// They represent fictional Eurovision entries and should remain
// in the language generated by the game.
//
// Only the genre name is localized.
//

export function translateSong(
  song: {
    title: string
    artist: string
    genre: {
      name: string
      song: number
      staging: number
    }
    native: boolean
    veteran: boolean
  },
  language: GameLanguage,
) {
  return {
    ...song,
    genre: {
      ...song.genre,
      name: getGenreName(
        song.genre.name,
        language,
      ),
    },
  }
}

// ============================================================
// Country helper
// ============================================================

export function translateCountry(
  country: {
    id: string
    name: string
    city: string
    alternativeCities: string[]
  },
  language: GameLanguage,
) {
  return {
    ...country,
    name: getCountryName(
      country.id,
      country.name,
      language,
    ),
    city: getCityName(
      country.city,
      language,
    ),
    alternativeCities: country.alternativeCities.map(
      (city) => getCityName(city, language),
    ),
  }
}